### ISSUE TITLE
Deserialization doesn't work

### ISSUE THREAD

**Issue by eishorn3** [eishorn3/ProductManagement#1]
The Deserialization doesn't load the products in the console application.

The thrown Error Message is:
System.NotSupportedException: 'Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'Product'. Path: $[0] | LineNumber: 0 | BytePositionInLine: 2.'

The Deserialization should load the products with the properties of the derived classes.

**Comment by fabian-blum** [comment]
Maybe this setting does it in the correct behaviour
`JsonSerializerSettings settings = new JsonSerializerSettings { TypeNameHandling = TypeNameHandling.All };`
https://stackoverflow.com/questions/8513042/json-net-serialize-deserialize-derived-types

**Comment by fabian-blum** [comment]
remider for tomorrow: [JsonConstructor]

**Comment by fabian-blum** [comment]
https://github.com/eishorn3/ProductManagement/commit/aca26b704ca34a4e292276877e773be68b1202dc

Fixed. Issue can be closed
